== Removing boilerplate (Lombok)

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Java has a -- probably deserved -- reputation for being somewhat prone to boilerplate, obscuring the meaning of our code.
There are however a couple of techniques we can use to reduce the boilerplate load.

One of the most common areas of boilerplate is the getters and setters.
We can use project lombok to remove the necessity of writing these methods.

=== Solution

[source,bash]
----
git checkout tags/030-removing-boilerplate-lombok
mvn clean package jetty:run
----

=== Exercise

* in the `pom.xml`, add the following to `<dependencies>`:
+
[source,xml]
----
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.16.18</version>
    <scope>provided</scope>
</dependency>
----

* remove the getters and setters for `Owner#name` and add in its `@lombok.Getter` and `@lombok.Setter` annotations for its field instead:

+
[source,java]
----
@javax.jdo.annotations.Column(allowsNull = "false", length = 40)
@Property(editing = Editing.DISABLED)
@Title(prepend = "Object: ")
@Getter @Setter                 // <1>
private String name;
----
<1> added in, `getName()` and `setName()` removed

* do likewise for the `Owner#notes` property


== Removing boilerplate (Parameter names)

Apache Isis uses Java reflection to infer the names of domain object types and members.
However, prior to Java 8 the name of method parameters was not accessible, and thus an annotation is required to provide this information.

For example, the `Owners#findByName(...)` action is:

[source,java]
----
public class Owners {

    @Action(semantics = SemanticsOf.NON_IDEMPOTENT)
    @MemberOrder(sequence = "1")
    public Owner create(
            @Parameter(maxLength = 40)
            @ParameterLayout(named = "Name")
            final String name) {
        return repositoryService.persist(new Owner(name));
    }
    ...
}
----

The boilerplate here is the `@ParameterLayout#named` annotation.

Given we're running on Java 8, though, we can remove this boilerplate.
We do so by configuring the framework to also check for Java 8 metadata.


=== Solution

[source,bash]
----
git checkout tags/040-removing-boilerplate--Paraname8
mvn clean package jetty:run
----




